# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Brent Fitzgerald 
tagline:             ''
description:         'Software developer in Oakland, CA, USA'
url:                 http://brentfitzgerald.com
baseurl:             ''
paginate:            1

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

analytics_id:        UA-452652-1

repository: burnto/brentfitzgerald.com

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
