# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Brent Fitzgerald 
# tagline:             'A Jekyll theme'
description:         'This is my website'
url:                 http://brentfitzgerald.com
baseurl:             ''
paginate:            5

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

analytics_id:        UA-452652-1

repository: burnto/brentfitzgerald.com
